server:
  port: ${registry-center.port}    # 配置eureka服务器端口号
spring:
  application:
    name: registry-center          # 指定该Eureka实例的应用名  registry-center
eureka:
  instance:
    prefer-ip-address: true        # 指定使用IP地址进行注册（Eureka默认是使用hostname进行注册的）
  client:
    register-with-eureka: false    # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetch-registry: false          # 表示是否从eureka服务器获取注册信息，同上，这里不需要
    serviceUrl:
      defaultZone: http://${registry-center.address}:${registry-center.port}/eureka/  # 设置eureka服务器所在的地址，即指定服务注册中心的位置 ，服务注册和发现都需要依赖这个地址

